spring:
  application:
    name: COUNTRY
  datasource:
    username: postgres
    url: jdbc:postgresql://89.104.68.220:5432/mc_country
    password: Psql7355
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  data:
    redis:
      port: 6379
      host: 89.104.68.220

server:
  port: 8085

eureka:
  instance:
    hostname: 89.104.68.220
  client:
    service-url:
      defaultZone: http://89.104.68.220:8761/eureka

app:
  feignClient:
    url: "http://89.104.68.220:8080/api/v1"